
export default{
    GET_ALL_ARTICLES_PENDING : "GET_ALL_ARTICLES_PENDING",
    GET_ALL_ARTICLES_SUCCESS : "GET_ALL_ARTICLES_SUCCESS",
    GET_ALL_ARTICLES_FAILED : "GET_ALL_ARTICLES_FAILED",

    GET_ALL_ALBUMS_PENDING : "GET_ALL_ALBUMS_PENDING",
    GET_ALL_ALBUMS_SUCCESS : "GET_ALL_ALBUMS_SUCCESS",
    GET_ALL_ALBUMS_FAILED : "GET_ALL_ALBUMS_FAILED",
}


